export const USER_LOADING = 'USER_LADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOAD_FAIL = 'USER_LOAD_FAIL';

export const PUBLIC_STORIES_LOADING = 'PUBLIC_STORIES_LOADING';
export const PUBLIC_STORIES_LOADED = 'PUBLIC_STORIES_LOADED';
export const PUBLIC_STORIES_LOAD_FAIL = 'PUBLIC_STORIES_LOAD_FAIL';

export const USER_STORIES_LOADING = 'USER_STORIES_LOADING';
export const USER_STORIES_LOADED = 'USER_STORiES_LOADED';
export const USER_STORIES_LOAD_FAIL = 'USER_STORiES_LOAD_FAIL';

export const ALERT_ERROR = 'ALERT_ERROR';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';
